name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: clean cache swupd 
      run:  swupd bundle-add --quiet make network-basic mixer clr-installer sudo
            swupd clean --all --quiet
            
      
    
   
